In [3]:
import sqlite3
import pandas as pd

In [5]:
connection = sqlite3.connect(':memory:')

cursor = connection.cursor()

In [8]:
create_table_query = '''
create table student(
    id integer primary key autoincrement,
    name text,
    age integer,
    mlmarks integer,
    dlmarks integer
);
'''
cursor.execute(create_table_query)
print("table created")

table created

In [11]:
insert_data= '''
insert into student(name, age, mlmarks, dlmarks)
values
('bob', 20, 90,70),
('riya', 21, 50,100),
('mintu', 25, 90,40);
'''
cursor.execute(insert_data)
connection.commit()
print("data inserted")

data inserted

In [12]:
query = "select * from student;"
df = pd.read_sql(query, connection)
df

   id   name  age  mlmarks  dlmarks
0   1    bob   20       90       70
1   2   riya   21       50      100
2   3  mintu   25       90       40

In [15]:
update_query = "update student set mlmarks=100 where name='riya';"
cursor.execute(update_query)
connection.commit()

In [16]:
updated_df = pd.read_sql(query, connection)
updated_df

   id   name  age  mlmarks  dlmarks
0   1    bob   20       90       70
1   2   riya   21      100      100
2   3  mintu   25       90       40

In [17]:
cursor.close()
connection.close()